---
version: '2'
services:
  mqtt:
    image: minio/minio
    hostname: minio
    container_name: minio
    ports:
      - 9000:9000
    volumes:
      - ./minio/data:/data
    command: server /data
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: adminadmin
